# ----------------------------
# Makefile Options
# ----------------------------

NAME = GGMACH
DESCRIPTION = "GGCE machine test"
COMPRESSED = NO
ARCHIVED = NO

CFLAGS = -Wall -Wextra -Oz -DZ80_ASM
CXXFLAGS = -Wall -Wextra -Oz -DZ80_ASM
EXTRA_ASMSOURCES = ../../src/z80core.s

# ----------------------------

include $(shell cedev-config --makefile)
