#!/usr/bin/env python3
"""Writes ../src/workload.h holding a CP/M program (ZEXDOC) as a C array."""
import os
import sys

if len(sys.argv) != 2:
    sys.exit("usage: embed.py zexdoc.com")
data = open(sys.argv[1], "rb").read()
out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "src", "workload.h")
with open(out, "w") as f:
    f.write("/* Generated by cemu/embed.py from %s */\n" % os.path.basename(sys.argv[1]))
    f.write("static const unsigned char workload[%d] = {\n" % len(data))
    for i in range(0, len(data), 16):
        f.write("    " + ", ".join("0x%02X" % b for b in data[i:i + 16]) + ",\n")
    f.write("};\n")
print("wrote", out)
